<?php

namespace Database\Seeders;


use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->insert([
            array(
                'id' => 1,
                'flag' => '0',
                'name' => 'United States',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 2,
                'flag' => '0',
                'name' => 'Canada',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 3,
                'flag' => '0',
                'name' => 'Afghanistan',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 4,
                'flag' => '0',
                'name' => 'Albania',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 5,
                'flag' => '0',
                'name' => 'Algeria',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 6,
                'flag' => '0',
                'name' => 'American Samoa',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 7,
                'flag' => '0',
                'name' => 'Andorra',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 8,
                'flag' => '0',
                'name' => 'Angola',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 9,
                'flag' => '0',
                'name' => 'Anguilla',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 10,
                'flag' => '0',
                'name' => 'Antarctica',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 11,
                'flag' => '0',
                'name' => 'Antigua and/or Barbuda',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 12,
                'flag' => '0',
                'name' => 'Argentina',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 13,
                'flag' => '0',
                'name' => 'Armenia',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 14,
                'flag' => '0',
                'name' => 'Aruba',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 15,
                'flag' => '0',
                'name' => 'Australia',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 16,
                'flag' => '0',
                'name' => 'Austria',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 17,
                'flag' => '0',
                'name' => 'Azerbaijan',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 18,
                'flag' => '0',
                'name' => 'Bahamas',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 19,
                'flag' => '0',
                'name' => 'Bahrain',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 20,
                'flag' => '0',
                'name' => 'Bangladesh',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 21,
                'flag' => '0',
                'name' => 'Barbados',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 22,
                'flag' => '0',
                'name' => 'Belarus',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 23,
                'flag' => '0',
                'name' => 'Belgium',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 24,
                'flag' => '0',
                'name' => 'Belize',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 25,
                'flag' => '0',
                'name' => 'Benin',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 26,
                'flag' => '0',
                'name' => 'Bermuda',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 27,
                'flag' => '0',
                'name' => 'Bhutan',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 28,
                'flag' => '0',
                'name' => 'Bolivia',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 29,
                'flag' => '0',
                'name' => 'Bosnia and Herzegovina',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 30,
                'flag' => '0',
                'name' => 'Botswana',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 31,
                'flag' => '0',
                'name' => 'Bouvet Island',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 32,
                'flag' => '0',
                'name' => 'Brazil',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 33,
                'flag' => '0',
                'name' => 'British lndian Ocean Territory',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 34,
                'flag' => '0',
                'name' => 'Brunei Darussalam',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 35,
                'flag' => '0',
                'name' => 'Bulgaria',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 36,
                'flag' => '0',
                'name' => 'Burkina Faso',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 37,
                'flag' => '0',
                'name' => 'Burundi',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 38,
                'flag' => '0',
                'name' => 'Cambodia',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 39,
                'flag' => '0',
                'name' => 'Cameroon',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 40,
                'flag' => '0',
                'name' => 'Cape Verde',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 41,
                'flag' => '0',
                'name' => 'Cayman Islands',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 42,
                'flag' => '0',
                'name' => 'Central African Republic',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 43,
                'flag' => '0',
                'name' => 'Chad',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 44,
                'flag' => '0',
                'name' => 'Chile',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 45,
                'flag' => '0',
                'name' => 'China',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 46,
                'flag' => '0',
                'name' => 'Christmas Island',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 47,
                'flag' => '0',
                'name' => 'Cocos (Keeling) Islands',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 48,
                'flag' => '0',
                'name' => 'Colombia',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 49,
                'flag' => '0',
                'name' => 'Comoros',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 50,
                'flag' => '0',
                'name' => 'Congo',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 51,
                'flag' => '0',
                'name' => 'Cook Islands',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 52,
                'flag' => '0',
                'name' => 'Costa Rica',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 53,
                'flag' => '0',
                'name' => 'Croatia (Hrvatska)',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 54,
                'flag' => '0',
                'name' => 'Cuba',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 55,
                'flag' => '0',
                'name' => 'Cyprus',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 56,
                'flag' => '0',
                'name' => 'Czech Republic',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 57,
                'flag' => '0',
                'name' => 'Denmark',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 58,
                'flag' => '0',
                'name' => 'Djibouti',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 59,
                'flag' => '0',
                'name' => 'Dominica',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 60,
                'flag' => '0',
                'name' => 'Dominican Republic',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 61,
                'flag' => '0',
                'name' => 'East Timor',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 62,
                'flag' => '0',
                'name' => 'Ecudaor',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 63,
                'flag' => '0',
                'name' => 'Egypt',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 64,
                'flag' => '0',
                'name' => 'El Salvador',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 65,
                'flag' => '0',
                'name' => 'Equatorial Guinea',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 66,
                'flag' => '0',
                'name' => 'Eritrea',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 67,
                'flag' => '0',
                'name' => 'Estonia',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 68,
                'flag' => '0',
                'name' => 'Ethiopia',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 69,
                'flag' => '0',
                'name' => 'Falkland Islands (Malvinas)',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 70,
                'flag' => '0',
                'name' => 'Faroe Islands',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 71,
                'flag' => '0',
                'name' => 'Fiji',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 72,
                'flag' => '0',
                'name' => 'Finland',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 73,
                'flag' => '0',
                'name' => 'France',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 74,
                'flag' => '0',
                'name' => 'France, Metropolitan',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 75,
                'flag' => '0',
                'name' => 'French Guiana',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 76,
                'flag' => '0',
                'name' => 'French Polynesia',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 77,
                'flag' => '0',
                'name' => 'French Southern Territories',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 78,
                'flag' => '0',
                'name' => 'Gabon',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 79,
                'flag' => '0',
                'name' => 'Gambia',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 80,
                'flag' => '0',
                'name' => 'Georgia',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 81,
                'flag' => '0',
                'name' => 'Germany',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 82,
                'flag' => '0',
                'name' => 'Ghana',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 83,
                'flag' => '0',
                'name' => 'Gibraltar',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 84,
                'flag' => '0',
                'name' => 'Greece',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 85,
                'flag' => '0',
                'name' => 'Greenland',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 86,
                'flag' => '0',
                'name' => 'Grenada',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 87,
                'flag' => '0',
                'name' => 'Guadeloupe',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 88,
                'flag' => '0',
                'name' => 'Guam',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 89,
                'flag' => '0',
                'name' => 'Guatemala',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 90,
                'flag' => '0',
                'name' => 'Guinea',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 91,
                'flag' => '0',
                'name' => 'Guinea-Bissau',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 92,
                'flag' => '0',
                'name' => 'Guyana',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 93,
                'flag' => '0',
                'name' => 'Haiti',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 94,
                'flag' => '0',
                'name' => 'Heard and Mc Donald Islands',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 95,
                'flag' => '0',
                'name' => 'Honduras',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 96,
                'flag' => '0',
                'name' => 'Hong Kong',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 97,
                'flag' => '0',
                'name' => 'Hungary',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 98,
                'flag' => '0',
                'name' => 'Iceland',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 99,
                'flag' => '0',
                'name' => 'India',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 100,
                'flag' => '0',
                'name' => 'Indonesia',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 101,
                'flag' => '0',
                'name' => 'Iran',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 102,
                'flag' => '0',
                'name' => 'Iraq',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 103,
                'flag' => '0',
                'name' => 'Ireland',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 104,
                'flag' => '0',
                'name' => 'Israel',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 105,
                'flag' => '0',
                'name' => 'Italy',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 106,
                'flag' => '0',
                'name' => 'Ivory Coast',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 107,
                'flag' => '0',
                'name' => 'Jamaica',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 108,
                'flag' => '0',
                'name' => 'Japan',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 109,
                'flag' => '0',
                'name' => 'Jordan',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 110,
                'flag' => '0',
                'name' => 'Kazakhstan',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 111,
                'flag' => '0',
                'name' => 'Kenya',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 112,
                'flag' => '0',
                'name' => 'Kiribati',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 113,
                'flag' => '0',
                'name' => 'Korea, Democratic People\'s Republic of',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 114,
                'flag' => '0',
                'name' => 'Korea, Republic of',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 115,
                'flag' => '0',
                'name' => 'Kuwait',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 116,
                'flag' => '0',
                'name' => 'Kyrgyzstan',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 117,
                'flag' => '0',
                'name' => 'Lao People\'s Democratic Republic',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 118,
                'flag' => '0',
                'name' => 'Latvia',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 119,
                'flag' => '0',
                'name' => 'Lebanon',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 120,
                'flag' => '0',
                'name' => 'Lesotho',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 121,
                'flag' => '0',
                'name' => 'Liberia',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 122,
                'flag' => '0',
                'name' => 'Libyan Arab Jamahiriya',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 123,
                'flag' => '0',
                'name' => 'Liechtenstein',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 124,
                'flag' => '0',
                'name' => 'Lithuania',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 125,
                'flag' => '0',
                'name' => 'Luxembourg',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 126,
                'flag' => '0',
                'name' => 'Macau',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 127,
                'flag' => '0',
                'name' => 'Macedonia',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 128,
                'flag' => '0',
                'name' => 'Madagascar',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 129,
                'flag' => '0',
                'name' => 'Malawi',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 130,
                'flag' => '0',
                'name' => 'Malaysia',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 131,
                'flag' => '0',
                'name' => 'Maldives',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 132,
                'flag' => '0',
                'name' => 'Mali',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 133,
                'flag' => '0',
                'name' => 'Malta',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 134,
                'flag' => '0',
                'name' => 'Marshall Islands',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 135,
                'flag' => '0',
                'name' => 'Martinique',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 136,
                'flag' => '0',
                'name' => 'Mauritania',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 137,
                'flag' => '0',
                'name' => 'Mauritius',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 138,
                'flag' => '0',
                'name' => 'Mayotte',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 139,
                'flag' => '0',
                'name' => 'Mexico',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 140,
                'flag' => '0',
                'name' => 'Micronesia, Federated States of',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 141,
                'flag' => '0',
                'name' => 'Moldova, Republic of',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 142,
                'flag' => '0',
                'name' => 'Monaco',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 143,
                'flag' => '0',
                'name' => 'Mongolia',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 144,
                'flag' => '0',
                'name' => 'Montserrat',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 145,
                'flag' => '0',
                'name' => 'Morocco',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 146,
                'flag' => '0',
                'name' => 'Mozambique',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 147,
                'flag' => '0',
                'name' => 'Myanmar',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 148,
                'flag' => '0',
                'name' => 'Namibia',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 149,
                'flag' => '0',
                'name' => 'Nauru',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 150,
                'flag' => '0',
                'name' => 'Nepal',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 151,
                'flag' => '0',
                'name' => 'Netherlands',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 152,
                'flag' => '0',
                'name' => 'Netherlands Antilles',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 153,
                'flag' => '0',
                'name' => 'New Caledonia',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 154,
                'flag' => '0',
                'name' => 'New Zealand',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 155,
                'flag' => '0',
                'name' => 'Nicaragua',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 156,
                'flag' => '0',
                'name' => 'Niger',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 157,
                'flag' => '0',
                'name' => 'Nigeria',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 158,
                'flag' => '0',
                'name' => 'Niue',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 159,
                'flag' => '0',
                'name' => 'Norfork Island',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 160,
                'flag' => '0',
                'name' => 'Northern Mariana Islands',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 161,
                'flag' => '0',
                'name' => 'Norway',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 162,
                'flag' => '0',
                'name' => 'Oman',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 163,
                'flag' => '0',
                'name' => 'Pakistan',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 164,
                'flag' => '0',
                'name' => 'Palau',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 165,
                'flag' => '0',
                'name' => 'Panama',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 166,
                'flag' => '0',
                'name' => 'Papua New Guinea',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 167,
                'flag' => '0',
                'name' => 'Paraguay',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 168,
                'flag' => '0',
                'name' => 'Peru',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 169,
                'flag' => '0',
                'name' => 'Philippines',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 170,
                'flag' => '0',
                'name' => 'Pitcairn',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 171,
                'flag' => '0',
                'name' => 'Poland',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 172,
                'flag' => '0',
                'name' => 'Portugal',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 173,
                'flag' => '0',
                'name' => 'Puerto Rico',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 174,
                'flag' => '0',
                'name' => 'Qatar',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 175,
                'flag' => '0',
                'name' => 'Reunion',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 176,
                'flag' => '0',
                'name' => 'Romania',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 177,
                'flag' => '0',
                'name' => 'Russian Federation',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 178,
                'flag' => '0',
                'name' => 'Rwanda',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 179,
                'flag' => '0',
                'name' => 'Saint Kitts and Nevis',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 180,
                'flag' => '0',
                'name' => 'Saint Lucia',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 181,
                'flag' => '0',
                'name' => 'Saint Vincent and the Grenadines',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 182,
                'flag' => '0',
                'name' => 'Samoa',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 183,
                'flag' => '0',
                'name' => 'San Marino',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 184,
                'flag' => '0',
                'name' => 'Sao Tome and Principe',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 185,
                'flag' => '0',
                'name' => 'Saudi Arabia',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 186,
                'flag' => '0',
                'name' => 'Senegal',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 187,
                'flag' => '0',
                'name' => 'Seychelles',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 188,
                'flag' => '0',
                'name' => 'Sierra Leone',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 189,
                'flag' => '0',
                'name' => 'Singapore',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 190,
                'flag' => '0',
                'name' => 'Slovakia',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 191,
                'flag' => '0',
                'name' => 'Slovenia',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 192,
                'flag' => '0',
                'name' => 'Solomon Islands',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 193,
                'flag' => '0',
                'name' => 'Somalia',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 194,
                'flag' => '0',
                'name' => 'South Africa',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 195,
                'flag' => '0',
                'name' => 'South Georgia South Sandwich Islands',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 196,
                'flag' => '0',
                'name' => 'Spain',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 197,
                'flag' => '0',
                'name' => 'Sri Lanka',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 198,
                'flag' => '0',
                'name' => 'St. Helena',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 199,
                'flag' => '0',
                'name' => 'St. Pierre and Miquelon',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 200,
                'flag' => '0',
                'name' => 'Sudan',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 201,
                'flag' => '0',
                'name' => 'Suriname',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 202,
                'flag' => '0',
                'name' => 'Svalbarn and Jan Mayen Islands',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 203,
                'flag' => '0',
                'name' => 'Swaziland',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 204,
                'flag' => '0',
                'name' => 'Sweden',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 205,
                'flag' => '0',
                'name' => 'Switzerland',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 206,
                'flag' => '0',
                'name' => 'Syrian Arab Republic',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 207,
                'flag' => '0',
                'name' => 'Taiwan',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 208,
                'flag' => '0',
                'name' => 'Tajikistan',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 209,
                'flag' => '0',
                'name' => 'Tanzania, United Republic of',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 210,
                'flag' => '0',
                'name' => 'Thailand',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 211,
                'flag' => '0',
                'name' => 'Togo',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 212,
                'flag' => '0',
                'name' => 'Tokelau',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 213,
                'flag' => '0',
                'name' => 'Tonga',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 214,
                'flag' => '0',
                'name' => 'Trinidad and Tobago',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 215,
                'flag' => '0',
                'name' => 'Tunisia',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 216,
                'flag' => '0',
                'name' => 'Turkey',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 217,
                'flag' => '0',
                'name' => 'Turkmenistan',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 218,
                'flag' => '0',
                'name' => 'Turks and Caicos Islands',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 219,
                'flag' => '0',
                'name' => 'Tuvalu',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 220,
                'flag' => '0',
                'name' => 'Uganda',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 221,
                'flag' => '0',
                'name' => 'Ukraine',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 222,
                'flag' => '0',
                'name' => 'United Arab Emirates',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 223,
                'flag' => '0',
                'name' => 'United Kingdom',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 224,
                'flag' => '0',
                'name' => 'United States minor outlying islands',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 225,
                'flag' => '0',
                'name' => 'Uruguay',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 226,
                'flag' => '0',
                'name' => 'Uzbekistan',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 227,
                'flag' => '0',
                'name' => 'Vanuatu',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 228,
                'flag' => '0',
                'name' => 'Vatican City State',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 229,
                'flag' => '0',
                'name' => 'Venezuela',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 230,
                'flag' => '0',
                'name' => 'Vietnam',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 231,
                'flag' => '0',
                'name' => 'Virigan Islands (British)',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 232,
                'flag' => '0',
                'name' => 'Virgin Islands (U.S.)',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 233,
                'flag' => '0',
                'name' => 'Wallis and Futuna Islands',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 234,
                'flag' => '0',
                'name' => 'Western Sahara',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 235,
                'flag' => '0',
                'name' => 'Yemen',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 236,
                'flag' => '0',
                'name' => 'Yugoslavia',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 237,
                'flag' => '0',
                'name' => 'Zaire',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 238,
                'flag' => '0',
                'name' => 'Zambia',
                'img' => 'img.jpg',
            ),
            array(
                'id' => 239,
                'flag' => '0',
                'name' => 'Zimbabwe',
                'img' => 'img.jpg',
            )
        ]);



    }
}
